version: '2'

networks:
  net:

services:
  cad:
    image: google/cadvisor
    mem_limit: 64m
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - net
  grf:
    build: GRF
    mem_limit: 64m
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - net
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true
  pms:
    image: prom/prometheus
    mem_limit: 128m
    volumes:
      - ./PMS/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - net
  ini:
    build: INI
    depends_on:
      - grf
    networks:
      - net
