version: '2'
services:
    namenode:
        image: ak/hadoop
        hostname: namenode
        command: /namenode.sh
        volumes:
          - ./HADOOP/namenode.sh:/namenode.sh
    datanode:
        image: ak/hadoop
        command: hdfs datanode
    yarn:
        image: ak/hadoop
        hostname: yarn
        command: yarn resourcemanager
    worker:
        image: ak/hadoop
        command: yarn nodemanager
    mysql:
        image: percona/percona-server
        hostname: mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=metastore
          - MYSQL_USER=hive
          - MYSQL_PASSWORD=hive
    metastore:
        image: ak/hadoop
        hostname: metastore
        command: hive --service metastore
        depends_on:
          - mysql
    hive:
        image: ak/hadoop
        hostname: hive
        command: hive --service hiveserver2
        depends_on:
          - metastore
    presto:
        image: ak/hadoop
        hostname: presto
        command: /usr/lib/presto/bin/launcher run
        depends_on:
          - metastore
