version: '2'
services:
    hnn:
        image: ak/hadoop
        hostname: hnn
        command: /namenode.sh
        volumes:
          - ./HADOOP/namenode.sh:/namenode.sh
    hdn:
        image: ak/hadoop
        command: hdfs datanode
    hrm:
        image: ak/hadoop
        hostname: hrm
        command: yarn resourcemanager
    hnm:
        image: ak/hadoop
        command: yarn nodemanager
    msq:
        image: percona/percona-server
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=metastore
          - MYSQL_USER=hive
          - MYSQL_PASSWORD=hive
    hms:
        image: ak/hadoop
        hostname: hms
        command: hive --service metastore
        depends_on:
          - msq
    hhs:
        image: ak/hadoop
        hostname: hhs
        command: hive --service hiveserver2
        depends_on:
          - hms
          - hrm
    hps:
        image: ak/hadoop
        hostname: hps
        command: /usr/lib/presto/bin/launcher run
