version: '2'
services:
    hnn:
        build: .
        hostname: hnn
        command: hdfs namenode
    hdn:
        build: .
        command: hdfs datanode
    hrm:
        build: .
        hostname: hrm
        command: yarn resourcemanager
    hnm:
        build: .
        command: yarn nodemanager
    msq:
        image: percona/percona-server
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=metastore
          - MYSQL_USER=hive
          - MYSQL_PASSWORD=hive
    hms:
        build: .
        hostname: hms
        command: hive --service metastore
        depends_on:
          - msq
    hhs:
        build: .
        hostname: hhs
        command: hive --service hiveserver2
        depends_on:
          - hms
          - hrm
