version: '2'
services:
    hnn:
        ports:
          - "127.0.0.1:50070:50070"
    hrm:
        ports:
          - "127.0.0.1:8088:8088"
    hhs:
        ports:
          - "127.0.0.1:10002:10002"
