version: '2'
services:
    namenode:
        ports:
          - "127.0.0.1:50070:50070"
        volumes:
          - ./HADOOP/hdfs-site.xml:/usr/lib/hadoop/etc/hadoop/hdfs-site.xml:ro
          - ./HADOOP/core-site.xml:/usr/lib/hadoop/etc/hadoop/core-site.xml:ro
    datanode:
        volumes:
          - ./HADOOP/hdfs-site.xml:/usr/lib/hadoop/etc/hadoop/hdfs-site.xml:ro
          - ./HADOOP/core-site.xml:/usr/lib/hadoop/etc/hadoop/core-site.xml:ro
    yarn:
        ports:
          - "127.0.0.1:8088:8088"
        volumes:
          - ./HADOOP/hdfs-site.xml:/usr/lib/hadoop/etc/hadoop/hdfs-site.xml:ro
          - ./HADOOP/core-site.xml:/usr/lib/hadoop/etc/hadoop/core-site.xml:ro
          - ./HADOOP/yarn-site.xml:/usr/lib/hadoop/etc/hadoop/yarn-site.xml:ro
    worker:
        volumes:
          - ./HADOOP/hdfs-site.xml:/usr/lib/hadoop/etc/hadoop/hdfs-site.xml:ro
          - ./HADOOP/core-site.xml:/usr/lib/hadoop/etc/hadoop/core-site.xml:ro
          - ./HADOOP/yarn-site.xml:/usr/lib/hadoop/etc/hadoop/yarn-site.xml:ro
    metastore:
        volumes:
          - ./HIVE/hive-site.xml:/usr/lib/hive/conf/hive-site.xml:ro
    hive:
        ports:
          - "127.0.0.1:10002:10002"
        volumes:
          - ./HADOOP/hdfs-site.xml:/usr/lib/hadoop/etc/hadoop/hdfs-site.xml:ro
          - ./HADOOP/core-site.xml:/usr/lib/hadoop/etc/hadoop/core-site.xml:ro
          - ./HADOOP/yarn-site.xml:/usr/lib/hadoop/etc/hadoop/yarn-site.xml:ro
          - ./HIVE/hive-site.xml:/usr/lib/hive/conf/hive-site.xml:ro
          - ./SPARK/spark-env.sh:/usr/lib/spark/conf/spark-env.sh:ro
          - ./SPARK/log4j.properties:/usr/lib/spark/conf/log4j.properties:ro
    presto:
        ports:
          - "127.0.0.1:8080:8080"
        volumes:
          - ./PRESTO/node.properties:/usr/lib/presto/etc/node.properties:ro
          - ./PRESTO/config.properties:/usr/lib/presto/etc/config.properties:ro
          - ./PRESTO/log.properties:/usr/lib/presto/etc/log.properties:ro
          - ./PRESTO/jvm.config:/usr/lib/presto/etc/jvm.config:ro
          - ./PRESTO/hive.properties:/usr/lib/presto/etc/catalog/hive.properties:ro
